jquery1
krystianan/jquery pull request #1
Opened 2017-02-06 11:56 UTC by krystianan

2017-02-06 12:02 UTC, matwjablonski requested changes

2017-02-06 12:02 UTC, matwjablonski commented on jquery1/index.html
> +﻿<html>
add doctype

2017-02-06 12:02 UTC, matwjablonski commented on jquery1/index.html
> +﻿<html>
and lang attribute

2017-02-06 12:02 UTC, matwjablonski commented on jquery1/index.html
> +        </head>
remove one tab

2017-02-06 12:02 UTC, matwjablonski commented on jquery1/js/scripts.js
> +var span = $('span');
this and below code should be in your function which load dom document

2017-02-06 12:17 UTC, krystianan commented
change index
delete 'console.log('DOM załadowany - można się bawić');' because it was unnecessary

2017-02-07 12:09 UTC, matwjablonski requested changes

2017-02-07 12:09 UTC, matwjablonski commented on jquery1/js/scripts.js
> -$(function(){
why you delete it?

2017-02-07 12:58 UTC, krystianan commented on jquery1/js/scripts.js
> -$(function(){
it was copied from other file, not function that was needed in this task

2017-02-08 12:29 UTC, merged